-- DDL for Tanker Brew Admiral Capstone
-- Run this in Snowflake Worksheet to setup the environment

-- 1. Create Data Storage Objects
USE ROLE ALL_USERS_ROLE;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE DATAEXPERT_STUDENT;
USE SCHEMA NICOLASSTEEL;

-- Bronze Table for Raw AIS Data
CREATE TABLE IF NOT EXISTS DK_AIS_BRONZE (
    _TIMESTAMP TIMESTAMP_NTZ,
    TYPE_OF_MOBILE VARCHAR,
    MMSI INTEGER,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    NAVIGATIONAL_STATUS VARCHAR,
    ROT FLOAT,
    SOG FLOAT,
    COG FLOAT,
    HEADING INTEGER,
    IMO INTEGER,
    CALLSIGN VARCHAR,
    NAME VARCHAR,
    SHIP_TYPE VARCHAR,
    CARGO_TYPE VARCHAR,
    WIDTH INTEGER,
    LENGTH INTEGER,
    TYPE_OF_POSITION_FIXING_DEVICE VARCHAR,
    DRAUGHT FLOAT,
    DESTINATION VARCHAR,
    ETA VARCHAR,
    DATA_SOURCE_TYPE VARCHAR,
    A INTEGER,
    B INTEGER,
    C INTEGER,
    D INTEGER,
    DS DATE -- Partition Column
);

-- Optimization (Cluster by Date and MMSI for efficient queries)
-- ALTER TABLE DK_AIS_BRONZE CLUSTER BY (DS, MMSI);

-- 2. Verify Creation
SELECT * FROM DK_AIS_BRONZE LIMIT 10;
